# Generated by Django 6.0.1 on 2026-02-04 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'unique_together': {('product', 'location')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='locations',
            field=models.ManyToManyField(through='inventory.StockLevel', to='inventory.location'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('movement_type', models.CharField(choices=[('IN', 'Inbound (Supplier)'), ('OUT', 'Outbound (Sale/Waste)'), ('TR', 'Internal Transfer')], max_length=3)),
                ('unit_price_at_purchase', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_out', to='inventory.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement_in', to='inventory.location')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['product', 'timestamp'], name='inventory_s_product_d287c5_idx')],
            },
        ),
    ]
